project:
  type: website
  output-dir: docs
  resources:
    - cv-latex.pdf
    - cv-canva.pdf
    
website:
  title: ""
  favicon: favicon.ico
  navbar:
    pinned: false
    right:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: Maps.qmd
        text: Maps
      - href: ClimateArt.qmd
        text: Climate&Art
      - href: FemaleVoices.qmd
        text: FemaleVoices
      - href: Contact.qmd
        text: Contact
  page-footer:
    left: "©2026 · Built by Sabela with care, coffee <i class='bi bi-cup-hot-fill'></i> and <a href='https://quarto.org' target='_blank'>Quarto</a>"
    right: "<a href='https://www.linkedin.com/in/sabelasanfiz' target='_blank'><i class='bi bi-linkedin'></i></a> &nbsp; <a href='https://github.com/Sanfiz' target='_blank'><i class='bi bi-github'></i></a> &nbsp; <a href='https://bsky.app/profile/sabelasanfiz.bsky.social' target='_blank'><i class='bi bi-cloud-fill'></i></a> &nbsp; <a href='mailto:sabelsanfiz@gmail.com'><i class='bi bi-envelope-fill'></i></a>"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    smooth-scroll: true
    embed-resources: false
    lightbox: true

execute:
  echo: false

  