project:
  type: website
  output-dir: docs
  resources:
    - files/
    - favicon.png
    - favicon.ico
    - images/

website:
  title: "Sanfiz"
  favicon: favicon.png
  navbar: false

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    smooth-scroll: true
    embed-resources: false
    include-in-header:
      text: |
        <link rel="icon" type="image/x-icon" href="favicon.ico">
        <link rel="icon" type="image/png" href="favicon.png">
    include-before-body: header.html
    include-after-body: footer.html

execute:
  echo: false